version: '2'
services:
  frontend:
    build: frontend
    environment:
      - VITE_AUTH_API_URL=http://127.0.0.1:8080
    ports:
      - "4173:4173"
      
  authdb:
    image: mysql:latest
    environment:
      - MYSQL_USER=ksenchan
      - MYSQL_PASSWORD=ksenchan
      - MYSQL_DATABASE=authdb
      - MYSQL_ROOT_PASSWORD=ksenchan
    ports:
      - "3306:3306"
      
  auth:
    build: backend/auth
    restart: always
    environment:
      - DB_USER=ksenchan
      - DB_PASSWORD=ksenchan
      - DB_PORT=3306
      - DB_HOST=authdb
      - DB_NAME=authdb
      - JWT_SECRET=123khklh123
      - ALLOWED_ORIGINS=http://127.0.0.1:5173, http://localhost:5173
    ports:
      - "8080:8080"

  core:
    build: backend/kscore
    restart: always
    environment:
      - KSCORE_SERVICE_PORT=9000
    ports:
      - "9000:9000"